#!/bin/bash

echo "📁 TRANSFERENCIA DIRECTA DE ARCHIVOS"
echo "===================================="
echo ""
echo "Ya tienes el archivo: invitaciones-deploy.tar.gz"
echo ""
echo "1️⃣ **Conectar al servidor AWS:**"
echo "   - Ve a AWS Console → EC2 → Instancias"
echo "   - Busca la instancia: 3.140.201.39"
echo "   - Click 'Conectar' → 'Conexión de instancia EC2'"
echo ""
echo "2️⃣ **En el terminal del servidor, ejecutar:**"
echo ""
echo "# Descargar archivo (usa uno de estos métodos):"
echo ""
echo "# Método A: Si tienes el archivo en un servicio cloud"
echo "wget 'TU_LINK_DE_DESCARGA' -O invitaciones-deploy.tar.gz"
echo ""
echo "# Método B: Copiar y pegar el contenido base64"
echo "cat > invitaciones-deploy.tar.gz.b64 << 'EOF'"
echo "# (pegar contenido base64 aquí)"
echo "EOF"
echo "base64 -d invitaciones-deploy.tar.gz.b64 > invitaciones-deploy.tar.gz"
echo ""
echo "3️⃣ **Extraer y ejecutar:**"
echo "tar -xzf invitaciones-deploy.tar.gz"
echo "sudo apt update"
echo "sudo apt install -y docker.io docker-compose"
echo "sudo docker-compose -f docker-compose-simple.yml up -d --build"
echo ""
echo "4️⃣ **Verificar:**"
echo "sudo docker-compose -f docker-compose-simple.yml ps"
echo "curl http://localhost"