version: '3.8'

services:
  # Backend API simple (usando simple_main.py)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./static:/app/static
    networks:
      - app-network
    restart: unless-stopped

  # Nginx para servir archivos estáticos y proxy
  frontend:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge