#!/bin/bash

# Script para subir proyecto a GitHub y deployar desde el servidor

echo "🚀 DEPLOYMENT VÍA GITHUB"
echo "=========================="
echo ""
echo "1️⃣ **Subir a GitHub:**"
echo ""
echo "# Inicializar git (si no existe)"
echo "git init"
echo "git add ."
echo "git commit -m 'Sistema de invitaciones Universidad Panamericana'"
echo ""
echo "# Crear repositorio en GitHub y conectar"
echo "git branch -M main"
echo "git remote add origin https://github.com/TU_USUARIO/invitaciones-up.git"
echo "git push -u origin main"
echo ""
echo "2️⃣ **En el servidor AWS (via EC2 Instance Connect):**"
echo ""
echo "# Clonar repositorio"
echo "git clone https://github.com/TU_USUARIO/invitaciones-up.git"
echo "cd invitaciones-up"
echo ""
echo "# Instalar Docker"
echo "sudo apt update"
echo "sudo apt install -y docker.io docker-compose"
echo "sudo usermod -aG docker ubuntu"
echo ""
echo "# Ejecutar aplicación"
echo "sudo docker-compose -f docker-compose-simple.yml up -d --build"
echo ""
echo "3️⃣ **Verificar:**"
echo "sudo docker-compose -f docker-compose-simple.yml ps"
echo "curl http://localhost"
echo ""
echo "🌐 **Tu app estará en:** http://3.140.201.39"