#!/bin/bash

echo "🚀 DEPLOYMENT MANUAL PARA AWS"
echo "============================="

echo "⚠️  EJECUTA ESTOS COMANDOS UNO POR UNO EN EL SERVIDOR AWS:"
echo ""

echo "# 1. Resolver conflictos de Git"
echo "cd /home/ubuntu/invitaciones"
echo "git stash"
echo "git fetch origin"
echo "git reset --hard origin/main"
echo "git pull origin main"
echo ""

echo "# 2. Parar servicios existentes"  
echo "sudo docker-compose down 2>/dev/null || true"
echo "sudo docker stop \$(sudo docker ps -q) 2>/dev/null || true"
echo ""

echo "# 3. Crear docker-compose.yml simple"
echo "cat > docker-compose.yml << 'DOCKEREOF'"
echo "version: '3.8'"
echo ""
echo "services:"
echo "  backend:"
echo "    build:"
echo "      context: ./backend"
echo "      dockerfile: Dockerfile.simple"
echo "    ports:"
echo "      - \"8000:8000\""
echo "    volumes:"
echo "      - ./backend:/app"
echo "      - ./static:/app/static"
echo "    restart: unless-stopped"
echo ""
echo "  frontend:"
echo "    image: nginx:alpine"
echo "    ports:"
echo "      - \"80:80\""
echo "    volumes:"
echo "      - ./static:/usr/share/nginx/html"
echo "    restart: unless-stopped"
echo "DOCKEREOF"
echo ""

echo "# 4. Crear Dockerfile simple"
echo "cat > backend/Dockerfile.simple << 'DOCKERFILEEOF'"
echo "FROM python:3.11-slim"
echo ""
echo "WORKDIR /app"
echo ""
echo "RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*"
echo ""
echo "COPY requirements.txt ."
echo "RUN pip install --no-cache-dir -r requirements.txt"
echo ""
echo "COPY . ."
echo ""
echo "EXPOSE 8000"
echo ""
echo "CMD [\"python\", \"simple_main.py\"]"
echo "DOCKERFILEEOF"
echo ""

echo "# 5. Reconstruir y ejecutar"
echo "sudo docker-compose up -d --build"
echo ""

echo "# 6. Verificar estado"
echo "sleep 10"
echo "sudo docker-compose ps"
echo "curl -s http://localhost/health || echo 'Backend no responde'"
echo "curl -s http://localhost/ | head -1 || echo 'Frontend no responde'"
echo ""

echo "🎯 URLs después del deployment:"
echo "- Frontend: http://registro.iux.com.mx"
echo "- Confirmación: http://registro.iux.com.mx/confirmation.html"
echo "- Health: http://registro.iux.com.mx/health"