#!/bin/bash

echo "📋 COMANDOS MANUALES PARA EL SERVIDOR"
echo "====================================="
echo ""
echo "Conecta al servidor AWS y ejecuta estos comandos paso a paso:"
echo ""
echo "# 1. Crear estructura de directorios"
echo "mkdir -p ~/invitaciones/backend ~/invitaciones/static"
echo "cd ~/invitaciones"
echo ""
echo "# 2. Crear backend/simple_main.py"
echo "cat > backend/simple_main.py << 'EOF'"
cat /Users/christian/Invitaciones/backend/simple_main.py
echo "EOF"
echo ""
echo "# 3. Crear backend/requirements.txt"
echo "cat > backend/requirements.txt << 'EOF'"
echo "fastapi==0.104.1"
echo "uvicorn==0.24.0"
echo "pydantic==2.4.2"
echo "python-multipart==0.0.6"
echo "EOF"
echo ""
echo "# 4. Copiar archivos estáticos"
echo "# (Aquí deberás copiar manualmente el contenido de los archivos HTML)"
echo ""
echo "# 5. Crear Dockerfile.simple"
echo "cat > Dockerfile.simple << 'EOF'"
cat /Users/christian/Invitaciones/Dockerfile.simple
echo "EOF"
echo ""
echo "# 6. Crear docker-compose-simple.yml"
echo "cat > docker-compose-simple.yml << 'EOF'"
cat /Users/christian/Invitaciones/docker-compose-simple.yml
echo "EOF"
echo ""
echo "# 7. Instalar Docker y ejecutar"
echo "sudo apt update"
echo "sudo apt install -y docker.io docker-compose"
echo "sudo usermod -aG docker ubuntu"
echo "sudo docker-compose -f docker-compose-simple.yml up -d --build"
echo ""
echo "# 8. Verificar"
echo "sudo docker-compose -f docker-compose-simple.yml ps"
echo "curl http://localhost"